### ISSUE TITLE
linking against dylib not safe for use in application extensions

### ISSUE THREAD

**Issue by arnaudmeunier** [choefele/CCHDarwinNotificationCenter#1]
Great wrapper, thanks for sharing!

I'm receiving warnings when archiving my WatchKit Extension (linking against dylib not safe for use in application extensions). Using XCode 6.3.

Any idea how to fix this?

**Comment by choefele** [comment]
How do you include `CCHDarwinNotificationCenter`? Via CocoaPods? Do you use `use_frameworks`?

If using dynamic frameworks, you'll have to [configure your app extension](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html#//apple_ref/doc/uid/TP40014214-CH21-SW5) accordingly:

> To configure an app extension target to use an embedded framework, set the target’s “Require Only App-Extension-Safe API” build setting to Yes. If you don’t, Xcode reminds you to do so by displaying the warning “linking against dylib not safe for use in application extensions”.

**Comment by choefele** [comment]
Closing this for now. Please reopen if you have any more questions. Thanks
